name: Docker Image
on: push
jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build image
        env:
          PROGRAM_USER: SUPERUSER
        run: docker build -t hw-github-actions-test:0.0.1 .
      - name: push image
        run:  docker push ghcr.io/asstart/hw-github-actions-test:0.0.1
