name: Docker Image
on: push
jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push image
        uses: docker/build-push-action@v2.8.0
        with:
          push: true
          tags: ${{ github.actor }}/hw-github-actions-test:0.0.1