name: Docker Image
on: push
jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - name: build image
        uses: docker/build-push-action@v2.8.0
        with:
          push: false
          tags: {{ github.actor }}/hw-github-actions-test:0.0.1
