name: WF with syntax err
on: 
  push:
    branches:
      - 'release/*'
jobs:
  Err-wf:
    run-on: ubuntu-latest
    steps:
      - run: echo "This job should be invalid by workflow linter becaus it's run-on instead runs-on"
  