name: Lint Workflow files
on: [pull-request]
jobs:
  lint_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yaml", "".github/workflows/*.yml""]'